// titles.js

 export default [
      { value: '1', label: 'ด.ช.' },
      { value: '2', label: 'ด.ญ.' },
      { value: '3', label: 'นาย' },
      { value: '4', label: 'น.ส.' },
      { value: '5', label: 'นาง' },
      { value: '120', label: 'ม.ร.ว.' },
      { value: '121', label: 'ม.ล.' },
      { value: '122', label: 'หม่อม' },
      { value: '130', label: 'คุณหญิง' },
      { value: '131', label: 'ท่านผู้หญิง' },
      { value: '133', label: 'พ.ญ.คุณหญิง' },
      { value: '134', label: 'น.พ.' },
      { value: '135', label: 'พ.ญ.' },
      { value: '136', label: 'ท.พ.' },
      { value: '137', label: 'ท.ญ.' },
      { value: '138', label: 'สพ.' },
      { value: '139', label: 'สญ.' },
      { value: '144', label: 'ภก.' },
      { value: '145', label: 'ภญ.' },
      { value: '200', label: 'พล.อ.' },
      { value: '201', label: 'ว่าที่ พล.อ.' },
      { value: '202', label: 'พล.ท.' },
      { value: '203', label: 'ว่าที่ พล.ท.' },
      { value: '204', label: 'พล.ต.' },
      { value: '205', label: 'ว่าที่ พล.ต.' },
      { value: '206', label: 'พ.อ.พิเศษ' },
      { value: '207', label: 'ว่าที่ พ.อ.พิเศษ' },
      { value: '208', label: 'พ.อ.' },
      { value: '209', label: 'ว่าที่ พ.อ.' },
      { value: '210', label: 'พ.ท.' },
      { value: '211', label: 'ว่าที่ พ.ท.' },
      { value: '212', label: 'พ.ต.' },
      { value: '213', label: 'ว่าที่ พ.ต.' },
      { value: '214', label: 'ร.อ.' },
      { value: '215', label: 'ว่าที่ ร.อ.' },
      { value: '216', label: 'ร.ท.' },
      { value: '217', label: 'ว่าที่ ร.ท.' },
      { value: '218', label: 'ร.ต.' },
      { value: '219', label: 'ว่าที่ ร.ต.' },
      { value: '220', label: 'จ.ส.อ.' },
      { value: '221', label: 'จ.ส.ท.' },
      { value: '222', label: 'จ.ส.ต.' },
      { value: '223', label: 'ส.อ.' },
      { value: '224', label: 'ส.ท.' },
      { value: '225', label: 'ส.ต.' },
      { value: '351', label: 'พล.ร.อ.' },
      { value: '352', label: 'ว่าที่ พล.ร.อ.' },
      { value: '353', label: 'พล.ร.ท.' },
      { value: '354', label: 'ว่าที่ พล.ร.ท.' },
      { value: '355', label: 'พล.ร.ต.' },
      { value: '356', label: 'ว่าที่ พล.ร.ต.' },
      { value: '357', label: 'น.อ.พิเศษ' },
      { value: '358', label: 'ว่าที่ น.อ.พิเศษ' },
      { value: '359', label: 'น.อ.' },
      { value: '360', label: 'ว่าที่ น.อ.' },
      { value: '361', label: 'น.ท.' },
      { value: '362', label: 'ว่าที่ น.ท.' },
      { value: '363', label: 'น.ต.' },
      { value: '364', label: 'ว่าที่ น.ต.' },
      { value: '365', label: 'ร.อ.' },
      { value: '366', label: 'ว่าที่ ร.อ.' },
      { value: '367', label: 'ร.ท.' },
      { value: '368', label: 'ว่าที่ ร.ท.' },
      { value: '369', label: 'ร.ต.' },
      { value: '370', label: 'ว่าที่ ร.ต.' },
      { value: '371', label: 'พ.จ.อ.' },
      { value: '372', label: 'พ.จ.ท.' },
      { value: '373', label: 'พ.จ.ต.' },
      { value: '374', label: 'จ.อ.' },
      { value: '375', label: 'จ.ท.' },
      { value: '376', label: 'จ.ต.' },
      { value: '500', label: 'พล.อ.อ.' },
      { value: '501', label: 'ว่าที่ พล.อ.อ.' },
      { value: '502', label: 'พล.อ.ท.' },
      { value: '503', label: 'ว่าที่ พล.อ.ท.' },
      { value: '504', label: 'พล.อ.ต.' },
      { value: '505', label: 'ว่าที่ พล.อ.ต.' },
      { value: '506', label: 'น.อ.พิเศษ' },
      { value: '507', label: 'ว่าที่ น.อ.พิเศษ' },
      { value: '508', label: 'น.อ.' },
      { value: '509', label: 'ว่าที่ น.อ.' },
      { value: '510', label: 'น.ท.' },
      { value: '511', label: 'ว่าที่ น.ท.' },
      { value: '512', label: 'น.ต.' },
      { value: '513', label: 'ว่าที่ น.ต.' },
      { value: '514', label: 'ร.อ.' },
      { value: '515', label: 'ว่าที่ ร.อ.' },
      { value: '516', label: 'ร.ท.' },
      { value: '517', label: 'ว่าที่ ร.ท.' },
      { value: '518', label: 'ร.ต.' },
      { value: '519', label: 'ว่าที่ ร.ต.' },
      { value: '520', label: 'พ.อ.อ.' },
      { value: '521', label: 'พ.อ.ท.' },
      { value: '522', label: 'พ.อ.ต.' },
      { value: '523', label: 'จ.อ.' },
      { value: '524', label: 'จ.ท.' },
      { value: '525', label: 'จ.ต.' },
      { value: '526', label: 'พลฯ' },
      { value: '651', label: 'พล.ต.อ.' },
      { value: '652', label: 'ว่าที่ พล.ต.อ.' },
      { value: '653', label: 'พล.ต.ท.' },
      { value: '654', label: 'ว่าที่ พล.ต.ท.' },
      { value: '655', label: 'พล.ต.ต.' },
      { value: '656', label: 'ว่าที่ พล.ต.ต.' },
      { value: '657', label: 'พล.ต.จ.' },
      { value: '658', label: 'ว่าที่พล.ต.จ.' },
      { value: '659', label: 'พ.ต.อ. (พิเศษ)' },
      { value: '660', label: 'ว่าที่ พ.ต.อ.พิเศษ' },
      { value: '661', label: 'พ.ต.อ.' },
      { value: '662', label: 'ว่าที่ พ.ต.อ.' },
      { value: '663', label: 'พ.ต.ท.' },
      { value: '664', label: 'ว่าที่ พ.ต.ท.' },
      { value: '665', label: 'พ.ต.ต.' },
      { value: '666', label: 'ว่าที่ พ.ต.ต.' },
      { value: '667', label: 'ร.ต.อ.' },
      { value: '668', label: 'ว่าที่ ร.ต.อ.' },
      { value: '669', label: 'ร.ต.ท.' },
      { value: '670', label: 'ว่าที่ ร.ต.ท.' },
      { value: '671', label: 'ร.ต.ต.' },
      { value: '672', label: 'ว่าที่ ร.ต.ต.' },
      { value: '673', label: 'ด.ต.' },
      { value: '674', label: 'จ.ส.ต.' },
      { value: '675', label: 'ส.ต.อ.' },
      { value: '676', label: 'ส.ต.ท.' },
      { value: '677', label: 'ส.ต.ต.' },
      { value: '678', label: 'ห้างหุ้นส่วนจำกัด' },
      { value: '679', label: 'บริษัทจำกัด (มหาชน)' },
      { value: '680', label: 'บริษัทจำกัด' },
      { value: '681', label: 'ห้างหุ้นส่วนสามัญนิติบุคคล' },
      { value: '682', label: 'ธนาคาร' },
      { value: '683', label: 'บรรษัท' },
      { value: '684', label: 'ห้างร้าน' },
      { value: '685', label: 'รัฐวิสาหกิจ' },
      { value: '686', label: 'ราชการ' },
      { value: '687', label: 'สมาคม' },
      { value: '688', label: 'มูลนิธิ' },
      { value: '689', label: 'วัด' },
      { value: '750', label: 'อาคารชุด' },
      { value: '751', label: 'สหกรณ์' },
      { value: '752', label: 'นิติบุคคล' },
      { value: '753', label: 'บริษัท' },
      { value: '754', label: 'นาย' },
      { value: '755', label: 'บริษัท' },
      { value: '756', label: 'พลเอก' },
      { value: '757', label: 'เรืออากาศตรี' },
      { value: '758', label: 'เรืออากาศตรี' },
      { value: '759', label: 'สำนักงาน' },
      { value: '760', label: 'สำนักงาน' },
      { value: '761', label: 'สำนักงาน' },
      { value: '762', label: 'รองศาสตราจารย์ ดร.' },
      { value: '763', label: 'รองศาสตราจารย์ ดร.' },
      { value: '764', label: 'โรงเรียน' }
    ]
